version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  api:
    container_name: api-container
    build: .
    image: social-handler
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ./dist:/usr/node-projects/social-handler/dist
    ports:
      - 8080:8080
    command: npm start
    environment:
      - MONGO_URL=mongodb://mongo:27017/social-handler