name: github-actions
on: [push]
jobs:
  run-all-tests:
    runs-on: windows-latest
    steps:

      - name: Setup node and tests
        uses: actions/setup-node@v3
        with:
          node-version: 16
        run: npm i jest -G&&npm run test:ci

      - name: Coveralls
        uses: coveralls/app/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
